### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [cchoi12/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by cchoi12** [comment]
Hey Billy,

So I tested my app on my phone and did notice that it could use better zoom/touch function. So as you recommended I looked for the mobile meta tag (http://getbootstrap.com/css/#Overview). I inserted   `<meta name="viewport" content="width=device-width, initial-scale=0.5">`
into my `<head> </head>` section on my application.html.erb file. 

I have committed and pushed to Git and then pushed to Heroku. 

`<!DOCTYPE html>
<html>
<head>
  <title>Splurty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.5">**#Added this in**
</head>`

**Comment by BillyMassey** [comment]
Great Job! 👍
